// news actions
export const FETCH_ALL_EVENTS_REQUEST = 'FETCH_ALL_EVENTS_REQUEST';
export const FETCH_ALL_EVENTS_FAILURE = 'FETCH_ALL_EVENTS_FAILURE';

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';

export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';

export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAILULE = 'EVENT_DELETE_FAILULE';

export const EVENT_STATUS_UPDATE_SUCCESS = 'EVENT_STATUS_UPDATE_SUCCESS';
export const EVENT_STATUS_UPDATE_FAILULE = 'EVENT_STATUS_UPDATE_FAILULE';

export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS';
export const EVENT_UPDATE_FAILULE = 'EVENT_UPDATE_FAILULE';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
