// news actions
export const FETCH_FIVE_NEWS_REQUEST = 'FETCH_FIVE_NEWS_REQUEST';
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_FIVE_NEWS_FAILURE = 'FETCH_FIVE_NEWS_FAILURE';

export const FETCH_ONENEWS_REQUEST = 'FETCH_ONENEWS_REQUEST';
export const FETCH_ONENEWS_FAILURE = 'FETCH_ONENEWS_FAILURE';

export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';
export const CREATE_NEWS_FAILURE = 'CREATE_NEWS_FAILURE';
export const NEWS_DELETE_SUCCESS = 'NEWS_DELETE_SUCCESS';
export const NEWS_DELETE_FAILULE = 'NEWS_DELETE_FAILULE';
export const NEWS_STATUS_UPDATE_SUCCESS = 'NEWS_STATUS_UPDATE_SUCCESS';
export const NEWS_STATUS_UPDATE_FAILULE = 'NEWS_STATUS_UPDATE_FAILULE';

export const NEWS_UPDATE_SUCCESS = 'NEWS_UPDATE_SUCCESS';
export const NEWS_UPDATE_FAILULE = 'NEWS_UPDATE_FAILULE';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
