// news actions
export const FETCH_ALL_PUBLICATIONS_REQUEST = 'FETCH_ALL_PUBLICATIONS_REQUEST';
export const FETCH_ALL_PUBLICATIONS_FAILURE = 'FETCH_ALL_PUBLICATIONS_FAILURE';

export const FETCH_PUBLICATION_REQUEST = 'FETCH_PUBLICATION_REQUEST';
export const FETCH_PUBLICATION_FAILURE = 'FETCH_PUBLICATION_FAILURE';

export const CREATE_PUBLICATION_REQUEST = 'CREATE_PUBLICATION_REQUEST';
export const CREATE_PUBLICATION_SUCCESS = 'CREATE_PUBLICATION_SUCCESS';
export const CREATE_PUBLICATION_FAILURE = 'CREATE_PUBLICATION_FAILURE';

export const PUBLICATION_DELETE_SUCCESS = 'PUBLICATION_DELETE_SUCCESS';
export const PUBLICATION_DELETE_FAILULE = 'PUBLICATION_DELETE_FAILULE';

export const PUBLICATION_STATUS_UPDATE_SUCCESS = 'PUBLICATION_STATUS_UPDATE_SUCCESS';
export const PUBLICATION_STATUS_UPDATE_FAILULE = 'PUBLICATION_STATUS_UPDATE_FAILULE';

export const PUBLICATION_UPDATE_SUCCESS = 'PUBLICATION_UPDATE_SUCCESS';
export const PUBLICATION_UPDATE_FAILULE = 'PUBLICATION_UPDATE_FAILULE';
